server:
  port: 8123
  servlet:
    context-path: /api
    session:
     cookie:
      max-age: 2592000
spring:
  application:
    name: gzx-picture-backend
    version: 1.0.0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gzx_picture
    username: root
    password: 1234
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 5000
  session:
    store-type: redis
    time-to-live: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field-name: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
knife4j:
  enable: true
  openapi:
    title: 接口文档
    version: 1.0.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.gzx.gzxpicturebackend.controller
cos:
  client:
    host: https://xxxxxx-1333996088.cos.ap-guangzhou.myqcloud.com
    secretId: AKID78ze8c2X4YIrDON9kBSZTFoAJH5KOGyU
    secretKey: MWfeQzLUQ9j9oKgsrdCduyqWzTq5AJG3
    region: ap-guangzhou
    bucket: xxxxxx-1333996088
thread-pool:
  core-pool-size: 10
  max-pool-size: 20
  keep-alive-time: 60
  queue-capacity: 200
